### ISSUE TITLE
Color picker not reporting data for rgb hsl hsv

### ISSUE THREAD

**Issue by todd-prior** [aurelienpierreeng/ansel#69]
Likely a side effect of the work you are doing and you likely know .... Color picker seems to show the right color selected and represented in the patch and reports values for Lab and LCh but not the other options...   Observed after building Win version tonight...

**Comment by mediatechnologic** [comment]
Thank you Todd, I can confirm this too .
May be Aurelien can fix my reported color picker, display and export issues on this occasion?

Even the export of downscaled JPG or PNG images is not gamma correct.
This is REALLY an issue for all fine details in photos, because they will turn 
at least too dark and if it goes badly even with wrong color.

That is one reason, why I am using ImageMagick for sharpening all JPG-exports
gamma-correct specially for each output display (TV, projector, screen, web …)
and each output resolution. 
This output sharpening (filtering) is a basic requirement of sampling theorem
and is a function of image resolution, viewing distance, camera ISO and more.

**Comment by todd-prior** [comment]
Thanks for sharing all your info. I have not had time to go over it. I suspect it will make sense if I break it down... I started that one long link you shared but ran out of steam.....

**Comment by aurelienpierre** [comment]
> Even the export of downscaled JPG or PNG images is not gamma correct.
This is REALLY an issue for all fine details in photos, because they will turn
at least too dark and if it goes badly even with wrong color.

What ??? Please open a separate issue for this with more details, raw file, etc.

**Comment by aurelienpierre** [comment]
> Color picker seems to show the right color selected and represented in the patch and reports values for Lab and LCh but not the other options... Observed after building Win version tonight...

Yep, I'm aware of that.

**Comment by mediatechnologic** [comment]
> > Even the export of downscaled JPG or PNG images is not gamma correct.
> > This is REALLY an issue for all fine details in photos, because they will turn
> > at least too dark and if it goes badly even with wrong color.
> 
> What ??? Please open a separate issue for this with more details, raw file, etc.

Yes, in some minutes I will post details with test image and calculation methods
in the DT issue "sRGB export wrong without linear scaling calculation"
after my post here https://github.com/darktable-org/darktable/issues/13335#issuecomment-1384617215

**Comment by aurelienpierre** [comment]
Again, I don't understand. 

Interpolation, aka downscaling, is done in linear RGB no matter what, for exports as well as in previews. In the pixel pipeline, it's achieved by the "finalscale" module, which comes before the gamma one. 

So I'm not sure what is your "ground truth" here, but maybe that should be checked first.

**Comment by todd-prior** [comment]
I guess if you look at that checkerboard and see how it gets handled which do you believe to be true. The result offered now or the result you would get if the colors were converted to linear sRGB then averaged and then converted back. In one case the result is rose and the other it's a light green??? This is just for the picker but I think the post is extrapolating this to scaling

**Comment by mediatechnologic** [comment]
I understand, that not everybody likes synthetic images, because real world is much better. But for checking tools and understanding modules it is not bad. See Boris with his good [DT Episode 64](http://youtu.be/XC_xv_LtAQo)

In fact with DT v4.2.0 the color picker, the previews and the exports are wrong. It is not higly relevant, but somehow not calculated linear. Easy to check and see with a checkerboard image. Make this in Gimp and everything is OK. Even the small previews in the GUI and also with the very small previews in the "file open" menu.

I have updated DT export issue https://github.com/darktable-org/darktable/issues/13335#issuecomment-1384617215 as proposed with an image. Not a raw file, but a tif which is highly suitable and impressive for scaling tests.

**Comment by aurelienpierre** [comment]
Ok I see what's going on.

The finalscale (final interpolation) module goes before the gamma module, but the gamma module doesn't actually do what it says… It only converts the 32 bits float pipeline to 8 bits int.

The mistake comes from finalscale going after colourout, which contains the OETF to display/export space.

It's an easy fix that requires to reorder the pipeline by default, but will need a new version of this default order.

**Comment by aurelienpierre** [comment]
Pending a new pipeline order, this has been fixed like this :

1. The interpolation (finalscale) module is made visible in GUI : 
![Screenshot_20230121_203525](https://user-images.githubusercontent.com/2779157/213884240-5cc069e2-f007-4d0e-b447-6929e29dafd4.png)
2. The label in the module links to this explanation : https://ansel.photos/en/doc/modules/processing-modules/finalscale/
3. User may do the correction themselves if needed.

**Comment by mediatechnologic** [comment]
Thank you very much Aurelien. I like the method to link in the GUI to "Learn more" 
and even more your content on it with clear good explanations.

The hint to do now the final/output sharpening after downscaling is also good. Basically in the pipeline from camera sensor to display/print you need physically a lot of filtering and sharpening.  Most people do not know the technical reason, if, why and where in the pipeline sharpening does happen or is required.

**Comment by aurelienpierre** [comment]
Thanks. That's a perk of being the dictator of the doc…

**Comment by AlynxZhou** [comment]
While the exporting works now, color picker is still failed on RGB or HSV, any idea on where to find the problem?

**Comment by AlynxZhou** [comment]
I finally squeeze some time to try to fix it by myself: looks like @aurelienpierre previously dropped histogram profile, but forgot that color picker uses the histogram profile converted value, which are all zero now, it can be simply fixed by using display profile picked color.

![image](https://user-images.githubusercontent.com/8444615/222221189-f696ecc5-850f-4901-afa0-1d165f8975ff.png)

A PR will be followed soon.

**Comment by todd-prior** [comment]
> I finally squeeze some time to try to fix it by myself: looks like @aurelienpierre previously dropped histogram profile, but forgot that color picker uses the histogram profile converted value, which are all zero now, it can be simply fixed by using display profile picked color.
> 
> ![image](https://user-images.githubusercontent.com/8444615/222221189-f696ecc5-850f-4901-afa0-1d165f8975ff.png)
> 
> A PR will be followed soon.

Nice.
